In [26]:
import numpy as np

vector = np.array([1, 2, 3])
print(f"1D Array:\n{vector}")

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{matrix}")

1D Array:
[1 2 3]
2D Array:
[[1 2 3]
 [4 5 6]]


In [27]:
# Describe the details of the dataset

print(f"Vector Shape: {vector.shape}")
print(f"Matrix Shape: {matrix.shape}")

print("Vector NDim:", vector.ndim)
print("Matrix NDim:", matrix.ndim)

print("Vector Data Type:", vector.dtype)
print("Matrix Data Type:", matrix.dtype)

print("Vector Size:", vector.size)
print("Matrix Size:", matrix.size)

Vector Shape: (3,)
Matrix Shape: (2, 3)
Vector NDim: 1
Matrix NDim: 2
Vector Data Type: int64
Matrix Data Type: int64
Vector Size: 3
Matrix Size: 6


In [28]:
import pandas as pd

df = pd.read_csv("AWCustomers.csv")
df.head


<bound method NDFrame.head of        CustomerID Title FirstName MiddleName  LastName Suffix  \
0           21173   NaN      Chad          C      Yuan    NaN   
1           13249   NaN      Ryan        NaN     Perry    NaN   
2           29350   NaN     Julia        NaN  Thompson    NaN   
3           13503   NaN  Theodore        NaN     Gomez    NaN   
4           22803   NaN  Marshall          J      Shan    NaN   
...           ...   ...       ...        ...       ...    ...   
18356       25414   NaN     Grace          C    Bailey    NaN   
18357       11459   NaN     Tasha        NaN      Deng    NaN   
18358       12160   NaN    Jaclyn        NaN     Zhang    NaN   
18359       14353   NaN      Erin          I      Reed    NaN   
18360       16676   NaN    Amanda        NaN     Perry    NaN   

                 AddressLine1 AddressLine2            City  \
0          7090 C. Mount Hood          NaN      Wollongong   
1         3651 Willow Lake Rd          NaN         Shawnee   
2  

In [29]:
df[['Occupation', 'Education']]

Occupation        Education
0            Clerical        Bachelors
1            Clerical  Partial College
2            Clerical        Bachelors
3      Skilled Manual  Partial College
4      Skilled Manual  Partial College
...               ...              ...
18356  Skilled Manual  Graduate Degree
18357  Skilled Manual        Bachelors
18358  Skilled Manual  Partial College
18359        Clerical      High School
18360    Professional  Graduate Degree

[18361 rows x 2 columns]

In [30]:
df[df['Occupation'] == 'Professional']

CustomerID Title FirstName MiddleName LastName Suffix  \
13          22031   NaN     Jorge        NaN      Cai    NaN   
26          15473   NaN   Abigail        NaN  Jenkins    NaN   
52          26741   NaN   Nichole          J      Pal    NaN   
55          14050   NaN    Manuel          M    Lopez    NaN   
87          27193   NaN    Daniel          V   Miller    NaN   
...           ...   ...       ...        ...      ...    ...   
18297       23367   NaN     Haley          A  Ramirez    NaN   
18317       18244   NaN   Lindsay        NaN   Chande    NaN   
18322       13883   NaN   Brandon        NaN      Lal    NaN   
18328       14248   NaN     Misty          A     Tang    NaN   
18360       16676   NaN    Amanda        NaN    Perry    NaN   

                  AddressLine1 AddressLine2           City StateProvinceName  \
13          7952 Quartermaster          NaN     Wollongong   New South Wales   
26          4838 Second Street          NaN       Coronado        California   
52          2765 Robbins Place          NaN      Lane Cove   New South Wales   
55             2396 Ancona Ct.          NaN     Cloverdale   South Australia   
87                 6885 Auburn          NaN  Lincoln Acres        California   
...                        ...          ...            ...               ...   
18297  8634 Lake Meadow Circle          NaN       Issaquah        Washington   
18317      1288 Mt. Dias Blvd.          NaN  East Brisbane        Queensland   
18322      3577 Pembroke Court          NaN     Long Beach        California   
18328      2906 Hillcrest Ave.          NaN     Bellflower        California   
18360      7870 Orangewood Dr.          NaN      Grossmont        California   

       ...        Education    Occupation Gender MaritalStatus HomeOwnerFlag  \
13     ...        Bachelors  Professional      M             M             1   
26     ...        Bachelors  Professional      F             S             1   
52     ...        Bachelors  Professional      F             M             1   
55     ...  Graduate Degree  Professional      M             S             1   
87     ...  Graduate Degree  Professional      M             S             0   
...    ...              ...           ...    ...           ...           ...   
18297  ...        Bachelors  Professional      F             M             1   
18317  ...  Graduate Degree  Professional      F             M             1   
18322  ...        Bachelors  Professional      M             S             1   
18328  ...  Graduate Degree  Professional      F             M             1   
18360  ...  Graduate Degree  Professional      F             M             1   

      NumberCarsOwned NumberChildrenAtHome TotalChildren  YearlyIncome  \
13                  2                    0             2        133762   
26                  2                    0             0        137464   
52                  2                    1             1        130385   
55                  2                    0             0        131458   
87                  3                    0             0        136457   
...               ...                  ...           ...           ...   
18297               2                    0             2        128111   
18317               2                    1             2        130494   
18322               2                    0             0        137513   
18328               1                    1             2        136686   
18360               2                    0             0        136856   

       LastUpdated  
13      2017-03-06  
26      2017-03-06  
52      2017-03-06  
55      2017-03-06  
87      2017-03-06  
...            ...  
18297   2017-03-06  
18317   2017-03-06  
18322   2017-03-06  
18328   2017-03-06  
18360   2017-03-06  

[1603 rows x 24 columns]

In [31]:
df.isnull().sum()

CustomerID                  0
Title                   18260
FirstName                   0
MiddleName               7789
LastName                    0
Suffix                  18358
AddressLine1                0
AddressLine2            18050
City                        0
StateProvinceName           0
CountryRegionName           0
PostalCode                  0
PhoneNumber                 0
BirthDate                   0
Education                   0
Occupation                  0
Gender                      0
MaritalStatus               0
HomeOwnerFlag               0
NumberCarsOwned             0
NumberChildrenAtHome        0
TotalChildren               0
YearlyIncome                0
LastUpdated                 0
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18361 entries, 0 to 18360
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   CustomerID            18361 non-null  int64 
 1   Title                 101 non-null    object
 2   FirstName             18361 non-null  object
 3   MiddleName            10572 non-null  object
 4   LastName              18361 non-null  object
 5   Suffix                3 non-null      object
 6   AddressLine1          18361 non-null  object
 7   AddressLine2          311 non-null    object
 8   City                  18361 non-null  object
 9   StateProvinceName     18361 non-null  object
 10  CountryRegionName     18361 non-null  object
 11  PostalCode            18361 non-null  object
 12  PhoneNumber           18361 non-null  object
 13  BirthDate             18361 non-null  object
 14  Education             18361 non-null  object
 15  Occupation            18361 non-null

In [33]:
df["Title"].fillna(df['Title'].mode()[0], inplace=True)

In [34]:
df

CustomerID Title FirstName MiddleName  LastName Suffix  \
0           21173   Mr.      Chad          C      Yuan    NaN   
1           13249   Mr.      Ryan        NaN     Perry    NaN   
2           29350   Mr.     Julia        NaN  Thompson    NaN   
3           13503   Mr.  Theodore        NaN     Gomez    NaN   
4           22803   Mr.  Marshall          J      Shan    NaN   
...           ...   ...       ...        ...       ...    ...   
18356       25414   Mr.     Grace          C    Bailey    NaN   
18357       11459   Mr.     Tasha        NaN      Deng    NaN   
18358       12160   Mr.    Jaclyn        NaN     Zhang    NaN   
18359       14353   Mr.      Erin          I      Reed    NaN   
18360       16676   Mr.    Amanda        NaN     Perry    NaN   

                 AddressLine1 AddressLine2            City  \
0          7090 C. Mount Hood          NaN      Wollongong   
1         3651 Willow Lake Rd          NaN         Shawnee   
2      1774 Tice Valley Blvd.          NaN     West Covina   
3             2103 Baldwin Dr          NaN       Liverpool   
4             Am Gallberg 234          NaN           Werne   
...                       ...          ...             ...   
18356      6627 Camelback Ct.          NaN        Coronado   
18357         9627 Kendall Rd          NaN  Port Macquarie   
18358       4364 Viera Avenue          NaN       Beaverton   
18359  3866 Mt. Everest Court          NaN       Vancouver   
18360     7870 Orangewood Dr.          NaN       Grossmont   

         StateProvinceName  ...        Education      Occupation Gender  \
0          New South Wales  ...        Bachelors        Clerical      M   
1         British Columbia  ...  Partial College        Clerical      M   
2               California  ...        Bachelors        Clerical      F   
3                  England  ...  Partial College  Skilled Manual      M   
4      Nordrhein-Westfalen  ...  Partial College  Skilled Manual      M   
...                    ...  ...              ...             ...    ...   
18356           California  ...  Graduate Degree  Skilled Manual      F   
18357      New South Wales  ...        Bachelors  Skilled Manual      F   
18358               Oregon  ...  Partial College  Skilled Manual      F   
18359     British Columbia  ...      High School        Clerical      F   
18360           California  ...  Graduate Degree    Professional      F   

      MaritalStatus HomeOwnerFlag NumberCarsOwned NumberChildrenAtHome  \
0                 M             1               3                    0   
1                 M             1               2                    1   
2                 S             0               3                    0   
3                 M             1               2                    1   
4                 S             1               1                    0   
...             ...           ...             ...                  ...   
18356             M             0               1                    0   
18357             S             0               2                    0   
18358             S             0               2                    0   
18359             S             0               0                    0   
18360             M             1               2                    0   

      TotalChildren  YearlyIncome  LastUpdated  
0                 1         81916   2017-03-06  
1                 2         81076   2017-03-06  
2                 0         86387   2017-03-06  
3                 2         61481   2017-03-06  
4                 0         51804   2017-03-06  
...             ...           ...          ...  
18356             2         52953   2017-03-06  
18357             0         60992   2017-03-06  
18358             0         51859   2017-03-06  
18359             0         87177   2017-03-06  
18360             0        136856   2017-03-06  

[18361 rows x 24 columns]

In [35]:
df["LastName"].count()

18361

In [36]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
print(type(diabetes))
print(diabetes)

<class 'sklearn.utils._bunch.Bunch'>
{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]]), 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 1

In [37]:
X = diabetes.data
y = diabetes.target

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)




X_train shape: (353, 10)
X_test shape: (89, 10)
y_train shape: (353,)
y_test shape: (89,)


In [38]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict (X_test)
y_pred[:5]

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872])

In [39]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 2900.193628493482
